version: '3.3'
services:
  movieapp:
    container_name: movieapp
    build: 
      context: ./movies_api
      dockerfile: Dockerfile
    env_file:
      - .env
    ports:
      - '8080:8080'
    restart: on-failure
    depends_on:
      - mysql_db
      - redis             

  mysql_db:
    image: mysql:latest
    container_name: mysql_movie_database
    ports: 
      - 4423:3306
    environment: 
      - MYSQL_DATABASE=${DB_DATABASE}
      - MYSQL_USER=${DB_USER_NAME}
      - MYSQL_PASSWORD=${DB_PASSWORD}
      - MYSQL_ROOT_PASSWORD=${DB_ROOT_PASSWORD}
    volumes:
      - ./database_mysql:/var/lib/mysql 
      - ./db:/docker-entrypoint-initdb.d

  redis:
    image: "redis:alpine"
    command: redis-server --requirepass ${REDIS_PASSWORD}
    ports:
      - "6379:6379"
    volumes:
      - $PWD/redis-data:/var/lib/redis
      - $PWD/redis.conf:/usr/local/etc/redis/redis.conf
    environment:
      - REDIS_REPLICATION_MODE=master
      
volumes:
  redis: